on:
  push:
  workflow_dispatch:    

jobs:
  hello_world_build:
    runs-on: ubuntu-latest
    name: A job to say hello.
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world Application
        uses: ./
        id: hello
        with:
          who-to-greet: 'Taha the great'
      - name: Get the Output
        run: |
          echo "The time was ${{ steps.hello.outputs.time }}"
    
